sudo: false
language: node_js
node_js:
  - "4"

before_script:
  - psql -c 'create database chaos_test;' -U postgres

after_script:
  - npm run coverage-report
  - npm run push-coverage
  - npm run cleanup
